
name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
    - name: Generate Release Hashes
      run: sha1sum build/libs/${{ github.event.repository.name }}.jar > hashes.txt
    - uses: actions/upload-artifact@v2
      with:
       name: Asset Hashes
       path: hashes.txt
    - name: Create Release
      if: strategy.job-index == 0
      id: create_release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: V ${{ github.run_number }}
          release_name: V ${{ github.run_number }}
          body: |
            Build ${{ github.run_number }} 
          draft: false
          prerelease: true
    - uses: xresloader/upload-to-github-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          file: "build/libs/ohiodustry.jar;hashes.txt"
          release_id: ${{ steps.create_release.outputs.id }}
          overwrite: true
          verbose: true
